//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosProcess
    {
        public System.Guid Guid { get; set; }
        public System.Guid GuidProduce { get; set; }
        public Nullable<System.Guid> ManufacturingBy { get; set; }
        public Nullable<System.DateTime> ManufacturingStartAt { get; set; }
        public Nullable<System.DateTime> ManufacturingEndAt { get; set; }
        public string History { get; set; }
        public Nullable<System.Guid> TransportBy { get; set; }
        public Nullable<System.DateTime> TransportStartAt { get; set; }
        public Nullable<System.DateTime> TransportEndAt { get; set; }
        public Nullable<System.Guid> DistributeBy { get; set; }
        public Nullable<System.DateTime> DistributeStartAt { get; set; }
        public Nullable<System.DateTime> DistributeEndAt { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> SignAt { get; set; }
        public string PublicKey { get; set; }
        public Nullable<int> ManufacturingStatus { get; set; }
        public Nullable<int> TransportStatus { get; set; }
        public Nullable<int> DistributeStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public string BigchainDBTransactionId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual PosProduce PosProduce { get; set; }
        public virtual SUser SUser { get; set; }
    }
}
