//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WLiveChat
    {
        public System.Guid Guid { get; set; }
        public string ChatMsg { get; set; }
        public string MsgSender { get; set; }
        public string MsgReceiver { get; set; }
        public int RecevierSeen { get; set; }
        public Nullable<System.DateTime> SendAt { get; set; }
    }
}
