//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOrderDetail
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> GuidOrder { get; set; }
        public Nullable<System.Guid> GuidProduce { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
    }
}
