//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOrder
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> GuidUser { get; set; }
        public string FullAddress { get; set; }
        public string Mobile { get; set; }
        public Nullable<long> PaymentTranId { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
